net/ftp-proxy: Fix php errors in ServiceController
Added checks to ensure $this->request is set before accessing it.

Error: Typed property OPNsense\Mvc\Controller::$request must not be accessed before initialization in /usr/local/opnsense/mvc/app/controllers/OPNsense/FtpProxy/Api/ServiceController.php:52